version: "3.9"

services:
  api:
    build: .
    container_name: ikicks-api
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    volumes:
    - ./:/app
    - /app/node_modules

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ikicks
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: